{% set name = "usaddress" %}
{% set version = "0.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/datamade/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a29b1bcaada285684948be1d1c19cf9ed7070284bb3ac0bb9a92531922d50982

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - parserator
  run:
    - python
    - python-crfsuite >=0.7
    - probableparsing

test:
  source_files:
    - tests
    - measure_performance/test_data
  imports:
    - usaddress
  requires:
    - pip
    - pytest
    - parserator
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -c "import usaddress; addr='123 Main St. Suite 100 Chicago, IL'; usaddress.parse(addr); usaddress.tag(addr)"
    - cp -r measure_performance/test_data "${SP_DIR}"
    - pytest -v tests

about:
  home: https://parserator.datamade.us/usaddress
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parse US addresses using conditional random fields
  description: Parse US addresses using conditional random fields
  doc_url: https://usaddress.readthedocs.io
  dev_url: https://github.com/datamade/usaddress

extra:
  recipe-maintainers:
    - wyseguy7
