{% set name = "usaddress" %}
{% set version = "0.5.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # tests and license are not in the tarball on pypi
  url: https://github.com/datamade/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ef83b69900fe490510fff6aa7239eef1b6a4ea4d00482c73ed4e75096da20f72

build:
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # requests is only used in an isolated script import_osm.py
    # - requests
    - future >=0.14
    - python-crfsuite >=0.7
    - probableparsing

test:
  imports:
    - usaddress
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    # ignore test_labeling.py because it depends on test files and it's about performance,
    # and test_tagging.py because one must train the model (parserator train --trainfile FILES) 
    # to create the usaddr.crfsuite file before one can use the parse and tag methods
    - pytest tests --ignore tests/test_labeling.py --ignore=tests/test_tagging.py

about:
  home: https://parserator.datamade.us/usaddress/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parse US addresses using conditional random fields
  description: Parse US addresses using conditional random fields
  doc_url: https://usaddress.readthedocs.io
  dev_url: https://github.com/datamade/usaddress

extra:
  recipe-maintainers:
    - wyseguy7
