travis:
  secure:
    BINSTAR_TOKEN: lmNZ0nLw9jvm/L8ITaQtV7qK3eq3Ig54Cr6kY1I1cK9Cv6pcyv5J31U5VgUe7GK2lqpDA4sp0olcrC9ELwZZEwc0k3ehJGCKTOVk2bdrLNM8icYeQjdasPCHHeTFHmt7s2D95P2JgaHdFJPqu44nJk8898LNtXAeOs5v9Q2wDq4Ij+RusE0G5Eh6HB4NndI/HlrFLgr4ianUgWmqU6osB0eM/ZuEEcXbVoGENrmOupjMZ7/QgtpY12LslufeKL/YZjovBaRoiBal2D1Dn4fIblHb+ML8aq62UxsP55erhrTx1UjWjDF4GyErAJPrhnyImcVKcO7cJDFr0Qhkghq2AysYc1MBQnrcVUNpnH/djMy3tGeF8PCtOnUhCNSeOvjrL65k5tDBrg0yBLqzTJK5BPgN/tAqEA40yZsJYN32L1gjYq92deBgeheiCOfen0c/qGgWvaYB4EgdEjxuyaS4UDHYBM2jR79Ed0SXQpDGQVGCntLqEH7ECoopH+Gv/t5j2CQd2pB4rGLdd6I7/D5YzmjO7boj06ICFTMqETIHczNufEkom1AsgyCUWuVZvl2LOV0o84O8pK/PzK41u1wlVJcQjjwwvQ+Iyk127IZtMXPWFO402/ks3FfU9/lgue7hDGn3c0AgU+pYd8xKYXayLIEO7/jWeQ5c03cqTdZipF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
