appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: d4HCzx3u71LmtWj1fbecS4d8EuiijWOeO9BHffp6/2l6Sis6TERbQzq+dG14hjElOxqexjBdquizRIpl0zkTyZU2lYBhbCSXYwdCJniNg3TH86tuCXZvmqCEPXBYpplcEAWFJou+YPhySTQuijD7MmMrKnn6rxeV4LXcWVkE7oKD/SzHMP8ZMmjxFE5KlNrKF5zicznVwtliLgACbP42D5QZfhJCoXOfN+ameQyLfp+8me7XuFuqQqXvuzigIPnqh/TtHlPOdtZxfIF632SA06z16Q986v5LpP4qA9W2jiG5h8NJMcWeSLCFPZapfi9gobgdoMdwcoH9UHObSuT3XdxGGp2hg9O52YAcUFAxHxvJCeABAmRgYcS5aCQt5nT3I0dQxLxF221gbxffoUHHdq6EeyQdU27AboxTyJlkz3ae9semxfU91wffGXGPZ+qp88D5hgN02YQbOr8+DY6deb3I/MYEfnslXeC1CIKLcm7+xuXHtIwrwnpXOBlIScRo5u2kVl4/ZNSIM5PSQuH5t1fSVVYwojXbcfFllGsXuW3OdEGnQTAeuGxbGHpeYvZ3K5hDZhjocmZt5cVGbDb9OAg/VDcjPiH+yrucLwEIip1jFFs7xtEd/DtSyI9B8Lpw+2BpstrcEgNs+sxCFR+mhtESNUHqz4oLVS6HSKZB0YU=}
provider:
  win: azure
